import { aggregateFunctions } from "../data/postgresql/aggregates";
import { operators } from "../data/postgresql/operators";
import { dataTypes } from "../data/postgresql/types";
import { userFunctions } from "../data/postgresql/user_functions";
import { other } from "../data/postgresql/other";

export const PostgreSQL = [
  ...aggregateFunctions,
  ...operators,
  ...dataTypes,
  ...userFunctions,
  ...other
];
export const importantPostgreSQLMethods=[
  "COUNT",
  "SUM",
  "AVG",
  "MIN",
  "MAX",
  "STRING_AGG",
  "ARRAY_AGG",
  "JSON_AGG",
  "JSONB_AGG",
  "JSON_OBJECT_AGG",
  "JSONB_OBJECT_AGG",
  "BOOL_AND (синоним EVERY)",
  "BOOL_OR",
  "ANY_VALUE",
  "STDDEV",
  "STDDEV_POP",
  "STDDEV_SAMP",
  "VARIANCE",
  "VAR_POP",
  "VAR_SAMP",
  "CORR",
  "COVAR_POP",
  "COVAR_SAMP",
  "REGR_AVGX",
  "REGR_AVGY",
  "REGR_COUNT",
  "REGR_INTERCEPT",
  "REGR_R2",
  "REGR_SLOPE",
  "REGR_SXX",
  "REGR_SXY",
  "REGR_SYY",
  "MODE",
  "PERCENTILE_CONT",
  "PERCENTILE_DISC",
  "RANK",
  "DENSE_RANK",
  "PERCENT_RANK",
  "CUME_DIST",
  "BIT_AND",
  "BIT_OR",
  "BIT_XOR",
  "XMLAGG",
  "RANGE_AGG",
  "RANGE_INTERSECT_AGG",
  "SELECT",
  "INSERT",
  "UPDATE",
  "DELETE",
  "RETURNING",
  "VALUES",
  "DISTINCT",
  "LIMIT",
  "OFFSET",
  "ORDER BY",
  "WHERE",
  "GROUP BY",
  "HAVING",
  "CREATE TABLE",
  "ALTER TABLE",
  "DROP TABLE",
  "TRUNCATE",
  "CREATE INDEX",
  "DROP INDEX",
  "CREATE VIEW",
  "DROP VIEW",
  "CREATE SEQUENCE",
  "DROP SEQUENCE",
  "INNER JOIN",
  "LEFT JOIN",
  "RIGHT JOIN",
  "FULL OUTER JOIN",
  "CROSS JOIN",
  "NATURAL JOIN",
  "BEGIN",
  "COMMIT",
  "ROLLBACK",
  "AS ",
  "IN",
  "BETWEEN",
  "IS NULL",
  "IS NOT NULL",
  "EXISTS",
  "CASE WHEN ... THEN ... ELSE ... END",
  "CAST ",
  "UNION",
  "UNION ALL",
  "WITH",
  "WITH RECURSIVE",
  "OVER",
  "PARTITION BY",
  "ORDER BY",
  "ROWS / RANGE BETWEEN",
  "LAG",
  "LEAD",
  "FIRST_VALUE",
  "LAST_VALUE",
  "NTH_VALUE",
  "ROW_NUMBER",
  "COPY ",
  "EXPLAIN ",
  "EXPLAIN ANALYZE",
  "VACUUM ",
  "ANALYZE ",
  "REINDEX",
  "CREATE MATERIALIZED VIEW",
  "REFRESH MATERIALIZED VIEW",
  "CREATE FUNCTION",
  "CREATE PROCEDURE",
  "CREATE TRIGGER",
  "CREATE TYPE",
  "CREATE DOMAIN",
  "CREATE EXTENSION",
  "COMMENT ON",
  "GRANT",
  "REVOKE",
  "CREATE ROLE",
  "CREATE USER",
  "ALTER ROLE",
  "DROP ROLE",
  "SHOW ",
  "SET",
  "ALTER SYSTEM ",
  "pg_hba.conf ",
  "postgresql.conf ",
  "LOCK TABLE",
  "SELECT ... FOR UPDATE",
  "SELECT ... FOR SHARE",
  "SELECT ... FOR NO KEY UPDATE",
  "SELECT ... FOR KEY SHARE",
  "SET TRANSACTION ISOLATION LEVEL",
  "PARTITION BY RANGE",
  "PARTITION BY LIST",
  "PARTITION BY HASH",
  "ATTACH PARTITION",
  "DETACH PARTITION",
  "tsvector",
  "tsquery",
  "@@ (Match operator)",
  "pg_dump",
  "pg_restore",
  "pg_basebackup",
  "WAL (Write-Ahead Logging)",
  "Logical Replication",
  "Physical Replication",
  "PUBLICATION",
  "SUBSCRIPTION",
  "TABLESPACE",
  "SCHEMA ",
  "LATERAL ",
  "TABLESAMPLE",
  "LISTEN",
  "NOTIFY",
  "PREPARE",
  "EXECUTE",
  "DEALLOCATE",
  "DO",
  "SECURITY DEFINER / INVOKER",
  "IMMUTABLE / STABLE / VOLATILE "
]